##Screen Graphics ##
image caimeo movie = Movie(play="caimeo/caimeotext1.webm", mask="caimeo/caimeotext1.webm")
image snow = Snow("screens/flake.png")
image til snowfore = "images/snowforegrond.png"
##Books##
image book1 = "items/book1.png"
image book1read1 = "images/items/books/book1.png"

#Lighting and shadows#
image cavelight = "images/lightingmaps/cave.png"
##Battle Graphics ##
image Eebee disabled = "ebee/fight/attack/eebee-fight0007.png"
image oleka disabled = "oleka/fight/attack/oleka0001.png"
image snaike disabled = "mobs/snaike/snaike0001.png"
image snaike blinded = "mobs/snaike/snaike0006.png"
## Eebee Graphics ##
#scene one##
image Eebee neutraltether = "ebee/animations/Eebee-neutral.png"
image Eebee wavetether = "ebee/animations/Eebee-wave.png"
image Eebee looktether = "ebee/animations/Eebee-lookdown.png"
image Eebee hmtether = "ebee/animations/Eebee-hm.png"
image Eebee wondertether = "ebee/animations/Eebee-wonder.png"
image Eebee snowed = "ebee/animations/Eebee-snowed.png"
image Eebee lookdown = "ebee/Eebee-lookdown.png"
image Eebee lookupworried ="ebee/Eebee-look-up-worried.png"
image Eebee panicked ="ebee/Eebee-panicked.png"
image Eebee winded ="ebee/Eebee-winded.png"
image Eebee winded2 ="ebee/Eebee-winded2.png"
image Eebee winded3 ="ebee/Eebee-winded3.png"
image Eebee winded4 ="ebee/Eebee-winded4.png"
image Eebee windedvhappy ="ebee/Eebee-winded-vhappy.png"
image Eebee windedsmiling ="ebee/Eebee-winded-smiling.png"
image Eebee windedworried = "ebee/Eebee-winded-worried.png"
image Eebee pickup = "ebee/Eebee-pickup.png"
image Eebee pickupbag = "ebee/Eebee-pickupright.png"
image Eebee pickuplefthurt = "ebee/Eebee-pickuplefthurt.png"
image Eebee happy = "ebee/Eebee-happy.png"
image Eebee happy2 = "ebee/Eebee-happy2.png"
image Eebee happybag = "ebee/Eebee-happy-bag.png"
image Eebee happybag2 = "ebee/Eebee-happy-bag2.png"
image Eebee pleased = "ebee/Eebee-pleased.png"
image Eebee pleased2 = "ebee/Eebee-pleased-bag.png"
image Eebee hurt = "ebee/Eebee-hurt.png"
image Eebee dazed = "ebee/Eebee-dazed.png"
image Eebee confused = "ebee/Eebee-confused.png"
image Eebee talk = "ebee/Eebee-talk.png"
image Eebee talk2 = "ebee/Eebee-talk2.png"
image Eebee talk3 = "ebee/Eebee-talk3.png"
image Eebee talkcoy = "ebee/Eebee-talkcoy.png"
# Scene two ##
image Eebee lampwonder = "ebee/Eebee-lampA.png"
image Eebee lampwonderpoint = "ebee/Eebee-lampB.png"
image Eebee lampwonderlook = "ebee/Eebee-lampC.png"
image Eebee lampwondertalk = "ebee/Eebee-lampD.png"
image Eebee lampwondertalk2 = "ebee/Eebee-lampE.png"
image Eebee lampwondertalk3 = "ebee/Eebee-lampF.png"
image Eebee lampwondergrossed = "ebee/Eebee-lampG.png"
image Eebee lampwonderonward = "ebee/Eebee-lampH.png"
image Eebee lampwonderlook2 = "ebee/Eebee-lampI.png"
image Eebee lampwonderlookback = "ebee/Eebee-lampJ.png"
image Eebee lampwonderturn = "ebee/Eebee-lampK.png"
image Eebee lampwonderlookback2 = "ebee/Eebee-lampL.png"
image Eebee lampanger = "ebee/Eebee-lampM.png"
image Eebee lampquestion = "ebee/Eebee-lampN.png"
image Eebee lampsmile = "ebee/Eebee-lampO.png"
#Oleka Graphics#
image oleka lookup1 = "oleka/oleka-lookup.png"
#misc#
image Eebee question = "ebee/Eebee-question.png"
image Eebee question2 = "ebee/Eebee-question2.png"
image Eebee vhappy = "ebee/Eebee-vhappy.png"
image Eebee mad = "ebee/Eebee-mad.png"
image Eebee huh = "ebee/Eebee-huh.png"
image Eebee huh2 = "ebee/eebee-huh2.png"
#items#
image chestopen = "images/items/chest/var1/chestopen.png"